name: Lint
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: 1.22.x

      - name: Verify formatting
        run: |
          make lint
          if [[ -n "$(git status --porcelain | grep -v 'argo-cd\|gitops-engine')" ]]; then
            echo "The following files have formatting issues:"
            git status --porcelain
            echo "Please run 'make lint' locally and commit the changes"
            exit 1
          fi
