name: Test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: v1.23.x 
     
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: recursive
      
      - name: Test
        run: go test ./...
